// Nextjs
import type { Metadata } from "next";

// Styles CSS
import "@/styles/globals.css";
import "@/styles/font-fix.css";

// Utility Functions
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/font-config";

// Layout Components
import { Header } from "@/components/layout/header";
import { SubHeader } from "@/components/layout/sub-header";
import { Footer } from "@/components/layout/footer";
import PageTransition from "@/components/layout/page-transition";
import NavTabs from "@/components/layout/nav-tabs";

// UI Components
import { ThemeProvider } from "@/components/ui/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "flex flex-col min-h-screen bg-background font-sans text-sm text-foreground antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <SubHeader />
          <NavTabs />
          <PageTransition>
            <main className="w-full max-w-xl mx-auto px-8">{children}</main>
          </PageTransition>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
